// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAMAx45C0a8ayRPQ5jXz5KOet5NR0LCx4',
    appId: '1:428446435658:web:fdb8259b2bc309b946d9b3',
    messagingSenderId: '428446435658',
    projectId: 'tikandtok-684cb',
    authDomain: 'tikandtok-684cb.firebaseapp.com',
    storageBucket: 'tikandtok-684cb.firebasestorage.app',
    measurementId: 'G-P43ZCT87R2',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCb8Cg8k-7S5_IfkVuEFNYpKQ5PbL2scAE',
    appId: '1:428446435658:ios:58b527dabcd2772246d9b3',
    messagingSenderId: '428446435658',
    projectId: 'tikandtok-684cb',
    storageBucket: 'tikandtok-684cb.firebasestorage.app',
    iosBundleId: 'com.heroiq.justsubmit-marcus',
  );

}